// src/components/scroll-to-top.svelte
<!-- svelte-ignore a11y-no-static-element-interactions -->
<!-- svelte-ignore a11y-click-events-have-key-events -->
<script>
  import { onDestroy, onMount } from "svelte";
  import scrollToTopImage from "/static/img/scroll-to-top.png?url";

  let showScroll = false;
  const checkScrollTop = () => {
    showScroll = window.scrollY > 25 * 16;
  };
  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };
  onMount(() => {
    window.addEventListener("scroll", checkScrollTop);
  });
  onDestroy(() => {
    window.removeEventListener("scroll", checkScrollTop);
  });
</script>

<div
  class={`h-24 w-24 bg-gray-800 hover:bg-gray-700 cursor-pointer rounded-full fixed grid place-items-center z-30 transition-all duration-300 ease-in-out bottom-8 right-8 ${showScroll ? "visible opacity-100" : "invisible opacity-0"}`}
  on:click={scrollToTop}
>
  <img src={scrollToTopImage} class="rotate-180" width="25" alt="" />
</div>

// src/components/scroll-to-top.tsx
import React, { useState, useEffect } from "react";
import ScrollToTopImage from "/static/img/scroll-to-top.png?url";

export const ScrollToTop: React.FC = () => {
  const [showScroll, setShowScroll] = useState<boolean>(false);

  const checkScrollTop = () => {
    if (!showScroll && window.scrollY > 25 * 16) {
      setShowScroll(true);
    } else if (showScroll && window.scrollY <= 25 * 16) {
      setShowScroll(false);
    }
  };

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  useEffect(() => {
    window.addEventListener("scroll", checkScrollTop);
    return () => window.removeEventListener("scroll", checkScrollTop);
  }, [showScroll]);

  return (
    <div
      className={`h-24 w-24 bg-gray-800 cursor-pointer rounded-full fixed grid place-items-center z-30 hover:bg-gray-700 ${
        showScroll ? "visible opacity-100" : "invisible opacity-0"
      } transition-all duration-300 ease-in-out bottom-8 right-8`}
      onClick={scrollToTop}
    >
      <img src={ScrollToTopImage} className="rotate-180" width={25} />
    </div>
  );
};
