// src/components/scroll-indicator.tsx
import React, { useState, useEffect } from "react";

export const ScrollIndicator: React.FC = () => {
  const [scrollPercentage, setScrollPercentage] = useState<number>(0);

  const updatePercentage = () => {
    const scrollHeight: number = document.documentElement.scrollHeight - window.innerHeight;
    const percentage: number = (window.scrollY / scrollHeight) * 100;
    setScrollPercentage(percentage);
  };

  useEffect(() => {
    window.addEventListener("scroll", updatePercentage);
    return () => {
      window.removeEventListener("scroll", updatePercentage);
    };
  });

  return (
    <div
      className="fixed inset-0 h-1 bg-blue-500"
      style={{ width: `${scrollPercentage}`, zIndex: 9999 }}
    ></div>
  );
};

// src/components/scroll-indicator.svelte
<script>
  import { onDestroy, onMount } from "svelte";

  let scrollPercentage = 0;
  const updatePercentage = () => {
    const scrollHeight = document.documentElement.scrollHeight - window.innerHeight;
    scrollPercentage = (window.scrollY / scrollHeight) * 100;
  };
  onMount(() => {
    window.addEventListener("scroll", updatePercentage);
  });
  onDestroy(() => {
    window.removeEventListener("scroll", updatePercentage);
  });
</script>

<div
  class="h-1 fixed inset-0 bg-blue-500 z-[9999]"
  style="width: {scrollPercentage}%"
></div>
